# Generated by Django 4.2.7 on 2025-07-17 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("knowledge", "0002_default_model_configs"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="file_name",
            field=models.CharField(default="", max_length=255, verbose_name="文件名"),
        ),
    ]
