# Generated by Django 4.2.7 on 2025-07-17 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("knowledge", "0003_document_file_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="modelconfig",
            name="description",
            field=models.TextField(blank=True, verbose_name="配置描述"),
        ),
    ]
