# Generated by Django 4.2.7 on 2025-07-17 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0005_alter_user_password"),
        ("knowledge", "0004_modelconfig_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="uploaded_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="user.user",
                verbose_name="上传者",
            ),
        ),
        migrations.AlterField(
            model_name="knowledgebase",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="user.user",
                verbose_name="创建者",
            ),
        ),
        migrations.AlterField(
            model_name="qasession",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="user.user",
                verbose_name="用户",
            ),
        ),
    ]
