# Generated by Django 4.2.7 on 2025-07-19 01:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0005_alter_user_password"),
    ]

    operations = [
        migrations.CreateModel(
            name="Achievement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="成就名称")),
                ("description", models.TextField(verbose_name="成就描述")),
                (
                    "icon",
                    models.CharField(
                        default="trophy", max_length=50, verbose_name="图标"
                    ),
                ),
                (
                    "achievement_type",
                    models.IntegerField(
                        choices=[
                            (1, "学习时长"),
                            (2, "课程完成"),
                            (3, "连续学习"),
                            (4, "知识探索"),
                            (5, "互动参与"),
                        ],
                        verbose_name="成就类型",
                    ),
                ),
                ("condition_value", models.IntegerField(verbose_name="达成条件数值")),
                ("points", models.IntegerField(default=0, verbose_name="奖励积分")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否启用"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "成就",
                "verbose_name_plural": "成就管理",
            },
        ),
        migrations.CreateModel(
            name="UserPoints",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "points",
                    models.IntegerField(
                        help_text="正数为获得，负数为扣减", verbose_name="积分变化"
                    ),
                ),
                (
                    "point_type",
                    models.IntegerField(
                        choices=[
                            (1, "学习课程"),
                            (2, "完成成就"),
                            (3, "连续登录"),
                            (4, "评论课程"),
                            (5, "分享课程"),
                        ],
                        verbose_name="积分类型",
                    ),
                ),
                ("description", models.CharField(max_length=200, verbose_name="描述")),
                (
                    "related_id",
                    models.IntegerField(
                        blank=True,
                        help_text="课程ID、成就ID等",
                        null=True,
                        verbose_name="关联ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="获得时间"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="user.user",
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "积分记录",
                "verbose_name_plural": "积分记录管理",
            },
        ),
        migrations.CreateModel(
            name="StudyStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "total_study_time",
                    models.IntegerField(default=0, verbose_name="总学习时长(分钟)"),
                ),
                (
                    "completed_courses",
                    models.IntegerField(default=0, verbose_name="完成课程数"),
                ),
                (
                    "continuous_days",
                    models.IntegerField(default=0, verbose_name="连续学习天数"),
                ),
                (
                    "max_continuous_days",
                    models.IntegerField(default=0, verbose_name="最大连续学习天数"),
                ),
                ("total_points", models.IntegerField(default=0, verbose_name="总积分")),
                (
                    "current_level",
                    models.IntegerField(default=1, verbose_name="当前等级"),
                ),
                (
                    "comments_count",
                    models.IntegerField(default=0, verbose_name="评论数量"),
                ),
                (
                    "favorites_count",
                    models.IntegerField(default=0, verbose_name="收藏数量"),
                ),
                (
                    "last_study_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="最后学习日期"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="user.user",
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "学习统计",
                "verbose_name_plural": "学习统计管理",
            },
        ),
        migrations.CreateModel(
            name="UserAchievement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "unlocked_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="获得时间"),
                ),
                ("progress", models.IntegerField(default=0, verbose_name="进度")),
                (
                    "is_completed",
                    models.BooleanField(default=False, verbose_name="是否完成"),
                ),
                (
                    "achievement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="user.achievement",
                        verbose_name="成就",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="user.user",
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "用户成就",
                "verbose_name_plural": "用户成就管理",
                "unique_together": {("user", "achievement")},
            },
        ),
    ]
